### ISSUE TITLE
Feedback on template resource sharing plan from an NIH grant proposal

### ISSUE THREAD

**Issue by dhimmel** [lab-carpentry/blueprint-resourcesharing#4]
Someone incorporated our template resource sharing plan in [`NIH-example.md`](https://github.com/lab-carpentry/blueprint-resourcesharing/blob/8a41caec57fe63dfcfd5db8213e10551306c1725/examples/NIH-example.md) into their NIH Grant proposal. Unfortunately, the proposal review deemed the resource sharing plans "unacceptable", with the following reason provided:

> The plan is very generic, and isn't specific to the results/software/code that will be produced during _this_ work. I was also not too excited about the suggestion that "All...code...will be made publicly available under an open license within two years of the end of the award." One would hope that the code, and the novel routines that will be generated during this award, would be made available as immediately as possible to enhance research by the entire community. 

Here is the text of the "Data Sharing Plan" from the grant, which includes additional paragraphs not in `NIH-example.md`. The University's name has been redacted (replaced with "_University_") to help maintain the proposal's anonymity:

> The _University_ is committed to the open and timely dissemination of research outcomes. Investigators in the proposed activity recognize that promising new methods, technologies, strategies and computer software may arise during the course of the research. The Investigators are aware of and agreed to abide by the principles for sharing research resources as described by NIH in Principles and Guidelines for Recipients of NIH Research Grants and Contracts on Obtaining and Disseminating Biomedical Research Resources.
> 
> While the investigators expect that research tools will be freely shared with the research community, opportunities for technology transfer through commercialization will be explored as appropriate. Working with the University community, the _University_, manages intellectual property at the _University_. _University_ serves faculty, staff and students by commercializing inventions, ideas and software developed at the University to ensure that new knowledge benefits society. _University_ works with researchers to assess the commercial potential of new ideas. _University_ goals are to disseminate new ideas so the public can benefit from discoveries, and to generate revenues for research and education. When the best means of disseminating discoveries and new intellectual property is collaboration between the University and commercial entities, _University_ has a special role to play. It protects the rights of the inventors and the University-and then typically works with industry, granting licenses so that a company will develop the discovery and bring it to the market. Revenues from licenses secured by _University_ are shared with the inventor, the inventors laboratory, and the inventors academic division. Where opportunities arise for corporate sponsored research related to the NIH-funded research programs, the University expects any agreements to conform to the principles described by NIH in the 1994 policy Developing Sponsored Research Agreements: Consideration for Recipients of NIH Research Grants and Contracts.
> 
> All outputs from this project including code, data, figures, documentation, and manuscripts will be made publicly available under an open license within two years of the end of the award. Code will be released under a BSD 3- Clause License, a permissive open source software license. Data will be released under the Creative Commons Public Domain Dedication (CC0, version 1.0 or later). Figures, documentation, and writing will be released under a Creative Commons Attribution License (version 4.0 or later).
> 
> In addition to the aforementioned licensing for project outputs, creators of specific project content may release any such content as CC0, at their individual discretion. The principal investigator of this project may release any project content as CC0, at his or her individual discretion.
> 
> In instances where upstream inputs are used that restrict the licensing of project outputs beyond the afore- mentioned guidelines, the most permissive licensing option possible will be applied. However, no inputs will be incorporated that prevent original software from being released under an Open Source Initiative (opensource.org) approved license or prevent original non-code content from being released under an Open Definition (opendefinition.org) conformant license.
> 
> Source code will be made available on a publicly accessible version control system, such as GitHub. Prior to submission of project manuscripts to a journal, all related outputs will be made publicly available under the aforementioned licensing guidelines and deposited to persistent archives. Currently, the group uses Zenodo for code repositories, figshare for datasets, and bioRxiv for preprints, however the group may transition to alternatives if other options become more suitable during the course of the grant. 

So that's a bummer that our resource sharing plan designed to guarantee openness was underwhelming to a reviewer. Let's take this opportunity to discuss how we can improve our template for the future.

**Comment by hakyim** [comment]
another reviewer thought this was unacceptable
> Resource Sharing Plans:
> Unacceptable
> - States that all outputs including code, data, figures, documentation, and manuscripts will be made publicly available under an open license within two years of the end of the award. It is not clear why 2 additional years after the end of the award are required. The tools would likely be nearing obsolescence at that point.

**Comment by dhimmel** [comment]
Okay so to recap, the Data Sharing Plan above was used in two separate grant proposals to the NIH's Genomics, Computational Biology and Technology Study Section. Both proposals received a negative review regarding the resource sharing plan. Specifically, the reviewers objected to the two-year window before open release of all materials is mandatory.

I think there are two issues that led to this situation:

1. The first two paragraphs in the resource sharing plan are not part of our template. Perhaps the _University_ required the inclusion of these paragraphs? These paragraphs are polished ways of saying that the University wants its "intellectually property" to be proprietary, such that it can sell usage rights to it. This is clear from the following sentences:

    > opportunities for technology transfer through commercialization will be explored as appropriate. ...
When the best means of disseminating discoveries and new intellectual property is collaboration between the University and commercial entities, University has a special role to play. It protects the rights of the inventors and the University-and then typically works with industry, granting licenses so that a company will develop the discovery and bring it to the market. 

    Ironically, the reason we designed this template was to guarantee that research outputs, which technically may be owned by the university, are released openly. Essentially, these first two paragraphs are antithetical to the template sharing plan. However, I think, even in this bizarre situation, our template would have performed well, and given the researchers the ability to openly disseminate the outputs from this grant, even if the _University_ wanted to act as a gatekeeper to the specific IP.

     Nonetheless, I imagine the juxtaposition of these motives confused the reviewers. Starting off with the scripted doublspeak which is basically a defense of making publicly-funded research outputs proprietary probably did not put the reviewers in the right mindset.

2. The reviewers seem to have missed that outputs would be made open "prior to submission of project manuscripts to a journal", which presumably would occur before two-years after the grant end date. I think we could do a better job communicating the current policy, so it's more obvious that it's a "whichever comes first" situation.

We should also consider reducing the 2-year deadline. Or perhaps templating it. For example, I make everything open immediately, since I perform all work in public repositories under open licenses. Users such as me probably want to be up front about this level of openness. However, for some types of research where secrecy is the norm prior to publication, I think the 2-year window is actually progressive.

I'd like for others to chime in and then I can go ahead and suggest revisions to the [template](https://github.com/lab-carpentry/blueprint-resourcesharing/blob/8a41caec57fe63dfcfd5db8213e10551306c1725/examples/NIH-example.md).

**Comment by hakyim** [comment]
In my template, I will just change "within two years of the end of the award" to "as soon as a stable version is available" 

I haven't tried to eliminate the preamble from the U, not sure worth the administrative burden (from my perspective)
